version: "3.8"
services:
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  database:
